name: Kaggle

on:

  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          cache: pip
          python-version: '3.7'
          
      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Exeute Notebook
        run: jupyter-execute KaggleTask_Competition_by_Artem_Khilalov.ipynb
        
      - name: Login to Kaggle
        run: |
              echo "KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }}" >> $GITHUB_ENV
              echo "KAGGLE_KEY=${{ secrets.KAGGLE_KEY }}" >> $GITHUB_ENV
              
      - name: Submit Predictions to Kaggle
        run: kaggle competitions submit -c titanic -f ./kaggle/survived.csv -m "Submition from GitHub"
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Artifact
          path: ./kaggle/survived.csv
